import { Car } from "../types/car";
import { hybrid, petrol } from "./fuel_types";
import { toyota } from "./manufacturers";

export const cars: Array<Car> = [
  {
    id: "1",
    title: "Toyota Camry",
    model: "Camry",
    year: 2020,
    color: "white",
    mileage: 20000,
    type: petrol,
    transmission: "automatic",
    price: 25000,
    drive: "front-wheel drive",
    engine: "2.5L 4-cylinder",
    condition: "used",
    vin: "1HGBH41JXMN109186",
    image: "/assets/images/bmw.png",
    manufacturer: toyota,
    build: "sedan",
  },
  // {
  //   id: "2",
  //   title: "Toyota Prius",
  //   model: "Prius",
  //   year: 2021,
  //   color: "blue",
  //   mileage: 15000,
  //   type: hybrid,
  //   transmission: "automatic",
  //   price: 30000,
  //   drive: "front-wheel drive",
  //   engine: "1.8L 4-C",
  //   condition: "used",
  //   vin: "1HGBH41JXMN109187",
  //   image: "/assets/images/bmw.png",
  //   manufacturer: toyota,
  //   build: "sedan",
  // },
  // {
  //   id: "3",
  //   title: "Toyota Prius",
  //   model: "Prius",
  //   year: 2021,
  //   color: "blue",
  //   mileage: 15000,
  //   type: hybrid,
  //   transmission: "automatic",
  //   price: 30000,
  //   drive: "front-wheel drive",
  //   engine: "1.8L 4-cylinder",
  //   condition: "used",
  //   vin: "1HGBH41JXMN109187",
  //   image: "/assets/images/bmw.png",
  //   manufacturer: toyota,
  //   build: "sedan",
  // },
  // {
  //   id: "4",
  //   title: "Toyota Prius",
  //   model: "Prius",
  //   year: 2021,
  //   color: "blue",
  //   mileage: 15000,
  //   type: hybrid,
  //   transmission: "automatic",
  //   price: 30000,
  //   drive: "front-wheel drive",
  //   engine: "1.8L 4-cylinder",
  //   condition: "used",
  //   vin: "1HGBH41JXMN109187",
  //   image: "/assets/images/bmw.png",
  //   manufacturer: toyota,
  //   build: "sedan",
  // },
  // {
  //   id: "5",
  //   title: "Toyota Prius",
  //   model: "Prius",
  //   year: 2021,
  //   color: "blue",
  //   mileage: 15000,
  //   type: hybrid,
  //   transmission: "automatic",
  //   price: 30000,
  //   drive: "front-wheel drive",
  //   engine: "1.8L 4-cylinder",
  //   condition: "used",
  //   vin: "1HGBH41JXMN109187",
  //   image: "/assets/images/bmw.png",
  //   manufacturer: toyota,
  //   build: "sedan",
  // },
  // {
  //   id: "4",
  //   title: "Toyota Prius",
  //   model: "Prius",
  //   year: 2021,
  //   color: "blue",
  //   mileage: 15000,
  //   type: hybrid,
  //   transmission: "automatic",
  //   price: 30000,
  //   drive: "front-wheel drive",
  //   engine: "1.8L 4-cylinder",
  //   condition: "used",
  //   vin: "1HGBH41JXMN109187",
  //   image: "/assets/images/bmw.png",
  //   manufacturer: toyota,
  //   build: "sedan",
  // },
  // {
  //   id: "5",
  //   title: "Toyota Prius",
  //   model: "Prius",
  //   year: 2021,
  //   color: "blue",
  //   mileage: 15000,
  //   type: hybrid,
  //   transmission: "automatic",
  //   price: 30000,
  //   drive: "front-wheel drive",
  //   engine: "1.8L 4-cylinder",
  //   condition: "used",
  //   vin: "1HGBH41JXMN109187",
  //   image: "/assets/images/bmw.png",
  //   manufacturer: toyota,
  //   build: "sedan",
  // },
  // {
  //   id: "4",
  //   title: "Toyota Prius",
  //   model: "Prius",
  //   year: 2021,
  //   color: "blue",
  //   mileage: 15000,
  //   type: hybrid,
  //   transmission: "automatic",
  //   price: 30000,
  //   drive: "front-wheel drive",
  //   engine: "1.8L 4-cylinder",
  //   condition: "used",
  //   vin: "1HGBH41JXMN109187",
  //   image: "/assets/images/bmw.png",
  //   manufacturer: toyota,
  //   build: "sedan",
  // },
  // {
  //   id: "5",
  //   title: "Toyota Prius",
  //   model: "Prius",
  //   year: 2021,
  //   color: "blue",
  //   mileage: 15000,
  //   type: hybrid,
  //   transmission: "automatic",
  //   price: 30000,
  //   drive: "front-wheel drive",
  //   engine: "1.8L 4-cylinder",
  //   condition: "used",
  //   vin: "1HGBH41JXMN109187",
  //   image: "/assets/images/bmw.png",
  //   manufacturer: toyota,
  //   build: "sedan",
  // },
  // {
  //   id: "4",
  //   title: "Toyota Prius",
  //   model: "Prius",
  //   year: 2021,
  //   color: "blue",
  //   mileage: 15000,
  //   type: hybrid,
  //   transmission: "automatic",
  //   price: 30000,
  //   drive: "front-wheel drive",
  //   engine: "1.8L 4-cylinder",
  //   condition: "used",
  //   vin: "1HGBH41JXMN109187",
  //   image: "/assets/images/bmw.png",
  //   manufacturer: toyota,
  //   build: "sedan",
  // },
  // {
  //   id: "5",
  //   title: "Toyota Prius",
  //   model: "Prius",
  //   year: 2021,
  //   color: "blue",
  //   mileage: 15000,
  //   type: hybrid,
  //   transmission: "automatic",
  //   price: 30000,
  //   drive: "front-wheel drive",
  //   engine: "1.8L 4-cylinder",
  //   condition: "used",
  //   vin: "1HGBH41JXMN109187",
  //   image: "/assets/images/bmw.png",
  //   manufacturer: toyota,
  //   build: "sedan",
  // },
  // {
  //   id: "4",
  //   title: "Toyota Prius",
  //   model: "Prius",
  //   year: 2021,
  //   color: "blue",
  //   mileage: 15000,
  //   type: hybrid,
  //   transmission: "automatic",
  //   price: 30000,
  //   drive: "front-wheel drive",
  //   engine: "1.8L 4-cylinder",
  //   condition: "used",
  //   vin: "1HGBH41JXMN109187",
  //   image: "/assets/images/bmw.png",
  //   manufacturer: toyota,
  //   build: "sedan",
  // },
  // {
  //   id: "5",
  //   title: "Toyota Prius",
  //   model: "Prius",
  //   year: 2021,
  //   color: "blue",
  //   mileage: 15000,
  //   type: hybrid,
  //   transmission: "automatic",
  //   price: 30000,
  //   drive: "front-wheel drive",
  //   engine: "1.8L 4-cylinder",
  //   condition: "used",
  //   vin: "1HGBH41JXMN109187",
  //   image: "/assets/images/bmw.png",
  //   manufacturer: toyota,
  //   build: "sedan",
  // },
  // {
  //   id: "4",
  //   title: "Toyota Prius",
  //   model: "Prius",
  //   year: 2021,
  //   color: "blue",
  //   mileage: 15000,
  //   type: hybrid,
  //   transmission: "automatic",
  //   price: 30000,
  //   drive: "front-wheel drive",
  //   engine: "1.8L 4-cylinder",
  //   condition: "used",
  //   vin: "1HGBH41JXMN109187",
  //   image: "/assets/images/bmw.png",
  //   manufacturer: toyota,
  //   build: "sedan",
  // },
  // {
  //   id: "5",
  //   title: "Toyota Prius",
  //   model: "Prius",
  //   year: 2021,
  //   color: "blue",
  //   mileage: 15000,
  //   type: hybrid,
  //   transmission: "automatic",
  //   price: 30000,
  //   drive: "front-wheel drive",
  //   engine: "1.8L 4-cylinder",
  //   condition: "used",
  //   vin: "1HGBH41JXMN109187",
  //   image: "/assets/images/bmw.png",
  //   manufacturer: toyota,
  //   build: "sedan",
  // },
  // {
  //   id: "4",
  //   title: "Toyota Prius",
  //   model: "Prius",
  //   year: 2021,
  //   color: "blue",
  //   mileage: 15000,
  //   type: hybrid,
  //   transmission: "automatic",
  //   price: 30000,
  //   drive: "front-wheel drive",
  //   engine: "1.8L 4-cylinder",
  //   condition: "used",
  //   vin: "1HGBH41JXMN109187",
  //   image: "/assets/images/bmw.png",
  //   manufacturer: toyota,
  //   build: "sedan",
  // },
  // {
  //   id: "5",
  //   title: "Toyota Prius",
  //   model: "Prius",
  //   year: 2021,
  //   color: "blue",
  //   mileage: 15000,
  //   type: hybrid,
  //   transmission: "automatic",
  //   price: 30000,
  //   drive: "front-wheel drive",
  //   engine: "1.8L 4-cylinder",
  //   condition: "used",
  //   vin: "1HGBH41JXMN109187",
  //   image: "/assets/images/bmw.png",
  //   manufacturer: toyota,
  //   build: "sedan",
  // },
];
